sudo: required
language: java
service:
  - docker

before_install:
  - docker build -t bartekwas/dockerspring .

script:
  - docker run -e CI=true bartekwas/dockerspring

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "dockerspring"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-docker-react"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $aws_ACCESS_KEY
#   secret_access_key: $_SECRET_KEY  
